homeassistant:
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.1.1.0/24
    - 172.50.0.0/16
    - 172.18.0.0/24

# Text to speech
tts:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include_dir_list lights
binary_sensor: !include_dir_list binary_sensors

homekit: !include homekit.yaml


notify:
  - name: brady_holly_iphones
    platform: group
    services:
      - service: mobile_app_bradys_iphone
      - service: mobile_app_holly_iphone

recorder:
  db_url: !secret database_pass

logger:
  default: warning

webostv:
  host: 10.1.20.30
  name: Master Bedroom TV
  #other settings
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret master_bedroom_webostv_mac
      broadcast_address: 10.1.20.30

wake_on_lan:
